apiVersion: v1
kind: Secret
metadata:
  name: github-access
  namespace: argo-events
type: Opaque
data:
  token: Z2hwX3JyTEFpOUtWTVF3VGdmcDYxOVp6a3U5OVk3NmJlNDNydzF5bA==
  user: ZWtyYWpjaGV2c2th
  email: ZXZhLmtyYWpjaGV2c2thQGdtYWlsLmNvbQ==