apiVersion: v1
kind: Secret
metadata:
  name: github-access
  namespace: argo-events
type: Opaque
data:
  token: Z2hwXzZJWUcwdGVqN2IybW8wcU5NVFBUVTNzcDc2amc5ODF3bGRraQ==
  user: ZWtyYWpjaGV2c2th
  email: ZXZhLmtyYWpjaGV2c2thQGdtYWlsLmNvbQ==