apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  creationTimestamp: "2021-07-18T11:48:26Z"
  finalizers:
  - sensor-controller
  generation: 1
  labels:
    example: "true"
  name: workflow
  namespace: argo-events
  resourceVersion: "11068"
  uid: a7032bf0-f29c-447c-b8d1-9e35a736433e
spec:
  dependencies:
  - name: github
    eventSourceName: github-event-source
    eventName: argo-gitops
    filters:
      data:
        - path: body.commits.0.message
          type: string
          comparator: "!="
          value:
            - "AutoUpgraded*"
  triggers:
  - template:
      name: github-workflow-trigger
      k8s:
        group: argoproj.io
        version: v1alpha1
        operation: create
        resource: workflows
        source:
          resource:
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
              generateName: argo-build-
              labels:
                workflows.argoproj.io/archive-strategy: "false"
            spec:
              entrypoint: build
              volumes:
              - name: kaniko-secret
                secret:
                  secretName: docker-registry-credentials
                  items:
                    - key: .dockerconfigjson
                      path: config.json
              - name: github-access
                secret:
                  secretName: github-access
                  items:
                    - key: token
                      path: token
                    - key: user
                      path: user
                    - key: email
                      path: email
              templates:
              - name: build
                dag:
                  tasks:
                  - name: run-unit-tests
                    template: unit-tests

                  - name: run-lint-check
                    template: lint-check

                  - name: run-format-check
                    template: format-check

                  - name: build-container-image
                    templateRef:
                      name: container-image
                      template: build-kaniko-git
                    arguments:
                      parameters:
                      - name: app_repo
                        value: git://github.com/stefankochev/argo-gitops
                      - name: container_image
                        value: stefankochev/argo-kaniko-test
                      - name: container_tag
                        value: "1.0.0"
                    dependencies:
                    - run-unit-tests
                    - run-lint-check
                    - run-format-check

                  - name: run-functional-tests
                    template: functional-tests
                    dependencies:
                    - build-container-image

                  - name: promote-staging
                    templateRef:
                      name: promote
                      template: promote
                    arguments:
                      parameters:
                      - name: environment
                        value: main
                      - name: repo_owner
                        value: stefankochev
                      - name: repo_name
                        value: argo-gitops
                      - name: image_owner
                        value: stefankochev
                      - name: image_name
                        value: "argo-kaniko-test"
                      - name: tag
                        value: "v1"
                    dependencies:
                    - run-functional-tests

              - name: lint-check
                script:
                  image: python:3.8
                  command: [sh]
                  source: |
                    echo "Cloning the repo..."

                    git clone https://github.com/stefankochev/argo-gitops.git
                    cd argo-gitops

                    echo "Installing requirements..."
                    pip install -r requirements.txt
                    
                    echo "Running lint check..."
                    flake8 app.py
                  volumeMounts:
                  - name: github-access
                    mountPath: /.github/

              - name: format-check
                script:
                  image: python:3.8
                  command: [sh]
                  source: |
                    echo "Cloning the repo..."

                    git clone https://github.com/stefankochev/argo-gitops.git
                    cd argo-gitops

                    echo "Installing requirements..."
                    pip install -r requirements.txt
                    
                    echo "Running format check with black formatter..."
                    black --check app.py
                  volumeMounts:
                  - name: github-access
                    mountPath: /.github/

              - name: unit-tests
                script:
                  image: python:3.8
                  command: [sh]
                  source: |
                    echo "Cloning the repo..."

                    git clone https://github.com/stefankochev/argo-gitops.git
                    cd argo-gitops

                    echo "Installing requirements..."
                    pip install -r requirements.txt
                    
                    echo "Running unit tests..."
                    pytest
                  volumeMounts:
                  - name: github-access
                    mountPath: /.github/

              - name: functional-tests
                script:
                  image: python:3.8
                  command: [sh]
                  source: |
                    echo "Cloning the repo..."

                    git clone https://github.com/stefankochev/argo-gitops.git
                    cd argo-gitops

                    echo "Installing requirements..."
                    pip install -r requirements.txt
                    
                    echo "Running functional tests..."
                    pytest
                  volumeMounts:
                  - name: github-access
                    mountPath: /.github/

  - template:
      log: {}
      name: log-1
  