apiVersion: v1
kind: Secret
metadata:
  name: github-access
  namespace: argo-events
type: Opaque
data:
  token: {BASE64_ENCODED_GITHUB_ACCESS_TOKEN_HERE}
  user: {BASE64_ENCODED_GITHUB_USERNAME_HERE}
  email: {BASE64_ENCODED_GITHUB_EMAIL_HERE}
