apiVersion: v1
kind: Secret
metadata:
  name: github-access
  namespace: argo-events
type: Opaque
data:
  token: Z2hwXzc0YUVURlFYc0p1aG1CM1JZc1loMHY5UnRUc21kZzBrSkJnbgo=
  user: ZWtyYWpjaGV2c2th
  email: ZXZhLmtyYWpjaGV2c2thQGdtYWlsLmNvbQ==