apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-api
  template:
    metadata:
      labels:
        app: flask-api
    spec:
      containers:
        - name: flask-api
          image: evgenija1/argo-app:af582b3a7b5ffd1f8144adfe300039efd7fc292c
          imagePullPolicy: 'IfNotPresent'
          ports:
            - containerPort: 5000
          env:
            - name: ENVIRONMENT
              value: staging