apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-api
  template:
    metadata:
      labels:
        app: flask-api
    spec:
      containers:
        - name: flask-api
          image: evgenija1/argo-app:a6cb77d06861ccead1fd2ac7f312228fd76321f0
          imagePullPolicy: 'IfNotPresent'
          ports:
            - containerPort: 5000
          env:
            - name: ENVIRONMENT
              value: staging