apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-api
  template:
    metadata:
      labels:
        app: flask-api
    spec:
      containers:
        - name: flask-api
          image: stefankochev/argo-kaniko-test:2fe57aaa47c5c5a63881911f785c23e94270b5b4
          imagePullPolicy: 'IfNotPresent'
          ports:
            - containerPort: 5000
          env:
            - name: ENVIRONMENT
              value: staging