apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-api
  template:
    metadata:
      labels:
        app: flask-api
    spec:
      containers:
        - name: flask-api
          image: stefankochev/argo-kaniko-test:6d5422cc688aa701b47a78037c5f5598d9e20f4c
          imagePullPolicy: 'IfNotPresent'
          ports:
            - containerPort: 5000
          env:
            - name: ENVIRONMENT
              value: staging