apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-api
  template:
    metadata:
      labels:
        app: flask-api
    spec:
      containers:
        - name: flask-api
          image: stefankochev/argo-kaniko-test:061a73669cd2e5859ff023cb35dc5ddd80f72249
          imagePullPolicy: 'IfNotPresent'
          ports:
            - containerPort: 5000
          env:
            - name: ENVIRONMENT
              value: staging