apiVersion: v1
kind: Service
metadata:
  name: flask-api-svc
  namespace: staging
  labels:
    app: flask-api
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: flask-api